config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  devise_for :users
  root 'groups#index'

  namespace :api do
    resources :messages, only: :index, defaults: { format: 'json' }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :members
  has_many :members
  has_many :messages

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  mount_uploader :image, ImageUploader

  validates :text, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, through: :members
  has_many :members
  has_many :messages

  validates :name, presence: true, length: { maximum: 6 }
  validates :email, presence: true
  validates :email, presence: true, length: { minimum: 6 }
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController

  def index
    @messages = Message.where(group_id: params[:group_id]).where('id > ?', params[:message_id]).includes(:user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :user_params, if: :devise_controller?

  def user_params 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.users << current_user
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to root_path, notice: 'グループを編集しました'
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :get_group

  def index
    set_index()
    @message = Message.new
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group) }
        format.json
      end
    else
      set_index()
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def get_group
    @group = Group.find(params[:group_id])
  end

  def set_index
    @groups = current_user.groups
    @messages = @group.messages.includes(:user)

    temp = []
    @group.users.each do |u|
      temp << u.name
    end
    @members = temp.join(' ')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit 
  end

  def update
    current_user.update(user_params)
    redirect_to root_path
  end

  def index
    @users = User.where('name like ?', "#{params[:keyword]}%" ).where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def user_params
    params['user'].permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do|message|
          %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, id: "chat_group_name", class: "chat-group-form__input", placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバーを追加
    .chat-group-form__field--right
      = text_field :user, :name, class: "chat-group-form__input", placeholder: "追加したいユーザーを入力してください"
      #chat-group-users
  .chat-group-form__field.clearfix
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-members
      - group.users.each do |user|
        .chat-group-member.clearfix.js-chat-member{id: "chat-group-user-#{user.id}"}
          %input{name: "group[user_ids][]", type: "hidden", value: "#{user.id}"}/
          %p.chat-group-user__name= user.name
          .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除


  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: "chat-group-form__action-btn"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "/groups/form", locals: { group: @group }

app/views/groups/index.html.haml
.contents
  = render partial: "/layouts/side_menu", locals: { groups: @groups }


  

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "/groups/form", locals: { group: @group }

app/views/layouts/_notification.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key 

app/views/layouts/_side_menu.html.haml
.side-menu
  .account
    %p.account__name 
      = current_user.name
    %p.account__icon
      = link_to "", new_group_path, class: "fa fa-edit icon-white"
      = link_to "", edit_user_path(current_user.id), class: "fa fa-cog icon-white"

  .group__list
    - groups.each do |group|
      = link_to "/groups/#{group.id}/messages", class: "group__list__elem" do
        %p.group__list__elem__title= group.name 
        - latest = group.messages.last
        - if latest.present? 
          %p.group__list__elem__latest-talk= latest.image.length > 0 ? "画像が投稿されています" : latest.text
        - else
          %p.group__list__elem__latest-talk まだメッセージがありません 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notification'
    = yield

app/views/messages/index.html.haml
.contents
  = render partial: "/layouts/side_menu", locals: { groups: @groups }

  .talks
    .talk__header
      .talk__header__info
        .talk__header__info__group= @group.name
        .talk__header__info__member= "Member : #{@members}"
      = link_to "Edit", edit_group_path(@group.id), class: "talk__header__edit"
    
    .talk__board
      - @messages.each do |message|
        .talk{ data: { 'message-id': message.id , 'message-group-id': message.group_id } }
          %p.talk__sender= message.user.name
          %p.talk__send_at= message.created_at.in_time_zone("Tokyo").strftime("%Y/%m/%d(%a) %H:%M:%S")
          %p.talk__text= message.text
          - if message.image.length > 0
            %p.talk__text
              = image_tag message.image, height: "150"

    = form_for [@group, @message], :url => {:action => 'create'} do |f|
      = f.text_field :text, class: "talk__form__text", placeholder: "type text"
      = f.label :image, class: "talk__form__image-label" do
        %i.fa.fa-picture-o
        = f.file_field :image, class: "talk__form__image-label__image"
      = f.submit "Send", class: "talk__form__submit", data: { disable_with: false }
    = hidden_field :current_user, :name

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user, :url => {:action => :update}) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/update.html.haml
%h1 更新しました